### ISSUE TITLE
Add tooling

### ISSUE THREAD

**Issue by sparten11740** [ExodusMovement/fetch#9]
- [x] run checks in the CI (#10)
- [x] add `@exodus/eslint-config` (https://github.com/ExodusMovement/fetch/pull/11)
- [x] use semrel to release automatically on merge to master (https://github.com/ExodusMovement/fetch/pull/13)

**Comment by sparten11740** [comment]
@ChALkeR are you okay with me adding some tooling here?

**Comment by ChALkeR** [comment]
No. This is a public repo and package, it shouldn't even dev-depend on private ones.

**Comment by sparten11740** [comment]
> it shouldn't even dev-depend on private ones

the two private dependencies it depends on will be open sourced soonish, so that shouldn't be an issue any more. Especially because this is a public repo there should be tooling that enforces standards.

**Comment by ChALkeR** [comment]
This can be unblocked once those are open-sourced.
Without that, this will introduce tooling that is broken instead.
